# Generated by Django 4.2.6 on 2023-11-06 11:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree_level', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_from', models.CharField(blank=True, max_length=20, null=True)),
                ('end_at', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='NewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ssc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('hsc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('bachelor_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('ielts_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('application_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('On Process', 'On Process'), ('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=30)),
                ('application_date', models.DateField(auto_now_add=True, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.intake')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.university')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='intakes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.intake'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.university'),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('stree', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='BookApointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Reject', 'Reject'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=30)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('hsc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('bachelor_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('ielts_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('statement', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('application_status', models.CharField(choices=[('Approve', 'Approved'), ('Reject', 'Reject'), ('On Process', 'On Process'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('application_date', models.DateField(auto_now_add=True, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.intake')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.university')),
            ],
        ),
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('ssc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('hsc_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('bachelor_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('ielts_certificate', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('statement', models.FileField(blank=True, null=True, upload_to='media/files')),
                ('application_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('On Process', 'On Process'), ('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=30)),
                ('application_date', models.DateField(auto_now_add=True, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.course')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.intake')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.university')),
            ],
        ),
    ]
