# Generated by Django 4.2.6 on 2023-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='intakes',
        ),
        migrations.AddField(
            model_name='course',
            name='intakes',
            field=models.ManyToManyField(to='backend.intake'),
        ),
    ]
