# Generated by Django 4.2.6 on 2023-11-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_course_intakes_course_intakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='intakes',
            field=models.ManyToManyField(to='backend.intake'),
        ),
    ]
