# Generated by Django 4.2.6 on 2023-11-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_university_intakes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewApplication',
        ),
    ]
