# Generated by Django 4.2.6 on 2023-11-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Reject', 'Reject'), ('On Process', 'On Process'), ('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
