# Generated by Django 4.2.6 on 2023-11-11 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_application_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='deatils',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
