# Generated by Django 4.2.6 on 2023-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_university_deatils'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
