# Generated by Django 4.2.6 on 2023-11-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_university_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='Country',
            field=models.CharField(choices=[('UK', 'UK'), ('USA', 'USA')], default=None, max_length=30),
        ),
    ]
