# Generated by Django 4.2.6 on 2023-11-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_university_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Local_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('School', 'School'), ('College', 'College')], default=None, max_length=30),
        ),
    ]
