# Generated by Django 4.2.6 on 2023-11-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_course_local_fees_university_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('School', 'School'), ('College', 'College')], default=None, max_length=30, null=True),
        ),
    ]
