# Generated by Django 4.2.6 on 2023-11-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_country_university_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='accept_student',
            field=models.CharField(blank=True, choices=[('HOME', 'HOME'), ('INTERNATIONAL', 'INTERNATIONAL')], default=None, max_length=30, null=True),
        ),
    ]
