# Generated by Django 4.2.6 on 2023-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_degreelevel_educationarea_studenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='accept_student',
        ),
        migrations.AddField(
            model_name='university',
            name='accept_student',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Foreign', 'Foreign'), ('Both', 'Both')], default=None, max_length=30, null=True),
        ),
    ]
