# Generated by Django 4.2.6 on 2023-11-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_university_accept_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentType',
        ),
    ]
