# Generated by Django 4.2.6 on 2023-11-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/images'),
        ),
    ]
