# Generated by Django 4.2.6 on 2023-11-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_pic',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='media/images'),
        ),
    ]
