# Generated by Django 4.2.6 on 2023-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Agent', 'Agent'), ('Student', 'Student'), ('partner', 'partner')], max_length=20),
        ),
    ]
