# Generated by Django 4.2.6 on 2023-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Agent', 'Agent'), ('Student', 'Student'), ('Partner', 'Partner')], max_length=20),
        ),
    ]
