# Generated by Django 4.2.6 on 2023-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_university_country'),
        ('accounts', '0006_alter_userprofile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='represented_universities',
            field=models.ManyToManyField(blank=True, null=True, related_name='partners', to='backend.university'),
        ),
    ]
