# Generated by Django 4.1 on 2023-11-24 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('event_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('event_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
