# Generated by Django 4.1 on 2023-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0002_blognews_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
