# Generated by Django 4.1 on 2023-11-24 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0003_alter_blognews_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
