# Generated by Django 4.1 on 2023-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0004_alter_blognews_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognews',
            name='event_link',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
