# Generated by Django 4.1 on 2023-11-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0005_remove_blognews_event_link_alter_events_event_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
