# Generated by Django 4.1 on 2023-11-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forntend', '0006_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('event_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
